### ISSUE TITLE
Stacked commands with terminal control/output fail to function properly

### ISSUE THREAD

**Issue by syntien** [tcsh-org/tcsh#10]
Issue (Mac OS X, latest):

    clear; ifconfig

This should clear the screen and write the output from ifconfig to the screen. Instead, it clears the screen and writes a garbled version of the output including some bell characters (audible beeps heard) followed by the remaining output of ifconfig.

**Comment by zoulasc** [comment]
On Oct 28, 10:05am, notifications@github.com (syntien) wrote:
-- Subject: [tcsh] Stacked commands with terminal control/output fail to func

| Issue (Mac OS X, latest):
| 
|     clear; ifconfig
| 
| This should clear the screen and write the output from ifconfig to the screen. Instead, it clears the screen and writes a garbled version of the output including some bell characters (audible beeps heard) followed by the remaining output of ifconfig.

Is that on terminal, xterm, what?
What does "echo $TERM" say?
Does "clear" by itself work properly?
Does the same work with bash/sh?

christos

**Comment by syntien** [comment]
> Is that on terminal, xterm, what?

Terminal.app. Interestingly, it does not fail in xterm (under XQuartz WM).

> What does "echo $TERM" say?

xterm-256color

> Does "clear" by itself work properly?

Yes.

> Does the same work with bash/sh?

Indeed it does (both). Only tcsh exhibits the bad behavior.

**Comment by zoulasc** [comment]
On Oct 28,  1:26pm, notifications@github.com (syntien) wrote:
-- Subject: Re: [tcsh] Stacked commands with terminal control/output fail to 

| > Is that on terminal, xterm, what?
| 
| Terminal.app. Interestingly, it does not fail in xterm (under XQuartz WM).
| 
| > What does "echo $TERM" say?
| 
| xterm-256color
| 
| > Does "clear" by itself work properly?
| 
| Yes.
| 
| > Does the same work with bash/sh?
| 
| Indeed it does (both). Only tcsh exhibits the bad behavior.

Weird, I can't reproduce this on 10.11.1... Can you run script before
you run those two commands and then exit and see what the typescript
contains?

Mine has:

<stuff before commands run><esc>[H<esc>[2Jlo0<stuff ifconfig prints>

which is the clear screen sequence for xterm... followed by lo0 which is
the first thing ifconfig prints.

christos

**Comment by syntien** [comment]
I don't have permission to upload files, so I've created a base64 encoded version of the typescript file here:

```
U2NyaXB0IHN0YXJ0ZWQgb24gV2VkIE9jdCAyOCAxNDoyMDoxNiAyMDE1ChtdMjtQYXVscy1N
YWNCb29rLUFpci5sb2NhbCA6IC9Vc2Vycy9wc2NvdHQHG10xO1BhdWxzLU1hY0Jvb2stQWly
LmxvY2FsB34gJWNsZWFyO2NhdCAvZXRjL2hvc3RzDQ0KG10yO1BhdWxzLU1hY0Jvb2stQWly
LmxvY2FsIDogY2xlYXIjIyAjIEhvc3QgRGF0YWJhc2UgIyAjIGxvY2FsaG9zdCBpcyB1c2Vk
IHRvIGNvbmZpZ3VyZSB0aGUgbG9vcGJhY2sgaW50ZXJmYWNlICMgd2hlbiB0aGUgc3lzdGVt
IGlzIGJvb3RpbmcuICBEbyBub3QgY2hhbmdlIHRoaXMgZW50cnkuICMjIDEyNy4wLjAuMQls
b2NhbGhvc3QgMjU1LjI1NS4yNTUuMjU1CWJyb2FkY2FzdGhvc3QgOjoxICAgICAgICAgICAg
IGxvY2FsaG9zdCAgZmU4MDo6MSVsbzAJbG9jYWxob3N0BxtbSBtbMkobXTI7UGF1bHMtTWFj
Qm9vay1BaXIubG9jYWwgOiBjbGVhciMjICMgSG9zdCBEYXRhYmFzZSAjICMgbG9jYWxob3N0
IGlzIHVzZWQgdG8gY29uZmlndXJlIHRoZSBsb29wYmFjayBpbnRlcmZhY2UgIyB3aGVuIHRo
ZSBzeXN0ZW0gaXMgYm9vdGluZy4gIERvIG5vdCBjaGFuZ2UgdGhpcyBlbnRyeS4gIyMgMTI3
LjAuMC4xCWxvY2FsaG9zdCAyNTUuMjU1LjI1NS4yNTUJYnJvYWRjYXN0aG9zdCA6OjEgICAg
ICAgICAgICAgbG9jYWxob3N0ICBmZTgwOjoxJWxvMAlsb2NhbGhvc3QHIyMNCiMgSG9zdCBE
YXRhYmFzZQ0KIw0KIyBsb2NhbGhvc3QgaXMgdXNlZCB0byBjb25maWd1cmUgdGhlIGxvb3Bi
YWNrIGludGVyZmFjZQ0KIyB3aGVuIHRoZSBzeXN0ZW0gaXMgYm9vdGluZy4gIERvIG5vdCBj
aGFuZ2UgdGhpcyBlbnRyeS4NCiMjDQoxMjcuMC4wLjEJbG9jYWxob3N0DQoyNTUuMjU1LjI1
NS4yNTUJYnJvYWRjYXN0aG9zdA0KOjoxICAgICAgICAgICAgIGxvY2FsaG9zdCANCmZlODA6
OjElbG8wCWxvY2FsaG9zdA0KG10yO1BhdWxzLU1hY0Jvb2stQWlyLmxvY2FsIDogL1VzZXJz
L3BzY290dAcbXTE7UGF1bHMtTWFjQm9vay1BaXIubG9jYWwHfiAlZXhpdA0NChtdMjtQYXVs
cy1NYWNCb29rLUFpci5sb2NhbCA6IC9Vc2Vycy9wc2NvdHQHG10xO1BhdWxzLU1hY0Jvb2st
QWlyLmxvY2FsB2V4aXQNCgpTY3JpcHQgZG9uZSBvbiBXZWQgT2N0IDI4IDE0OjIwOjIzIDIw
MTUK
```

Copy the text (line breaks and all) into a file named typescript.base64, and then run the command below to examine the output:

```
base64 -D typescript.base64 | less
```

Note that to keep the output to a minimum, I've changed the original command to `"clear;cat /etc/hosts"` but the result is the same (garbage and bell characters). This is on OS X 10.11.1, as well.

**Comment by zoulasc** [comment]
On Oct 28,  2:29pm, notifications@github.com (syntien) wrote:
-- Subject: Re: [tcsh] Stacked commands with terminal control/output fail to 

Looks like you have a precmd to set the xterm title and icon, (perhaps I am
guessing executing another command at each command invocation). The ^G is
coming from the end-of-sequence of that xterm command.
(http://tldp.org/HOWTO/Xterm-Title-3.html). It works in other shells because
you don't do that, and it works in xterm because it is processing things
different than Terminal does (or tcsh mangles the order of the output).
It is a lot better to:

	- don't `` in precmd; cache in a variable
	- only do one ^[]0 instead of two (^[]1 and ^[]2)
	- or do it in cwdcmd, it is a lot more efficient :-)
	  you could set $host in your .cshrc and then:
	  alias cwdcmd  'echo -n "^[]2;"$host":$cwd^G^[]1;${host}^G"'

christos

**Comment by syntien** [comment]
I should have seen that. The problem was the result of using jobcmd in a bad way. Sorry for the trouble, and grateful for the assistance!

**Comment by zoulasc** [comment]
On Oct 28,  3:39pm, notifications@github.com (syntien) wrote:
-- Subject: Re: [tcsh] Stacked commands with terminal control/output fail to 

| I should have seen that. The problem was the result of using jobcmd in a bad way. Sorry for the trouble, and grateful for the assistance!
| 

No problem, glad to be of help.

christos
