### ISSUE TITLE
[PATCH] Fix greek locale code

### ISSUE THREAD

**Issue by josefs10** [tcsh-org/tcsh#103]
Forwarding a debian patch to fix lintian warning [incorrect-locale-code.tag.txt](https://github.com/tcsh-org/tcsh/files/15325575/incorrect-locale-code.tag.txt). Thanks! @thep

[fix-greek-locale-code.patch.txt](https://github.com/tcsh-org/tcsh/files/15325553/fix-greek-locale-code.patch.txt)

**Comment by thep** [comment]
According to [ISO 639-2](https://www.loc.gov/standards/iso639-2/php/code_list.php), the Alpha-2 (ISO 639-1) language code for Greek is `el`, not `gr`. And resources for Greek locale are therefore generally installed in `/usr/share/locale/el/`.

Not just Debian, Fedora [appears to do the same](https://koji.fedoraproject.org/koji/rpminfo?rpmID=38577452).

**Comment by josefs10** [comment]
Closing as this was fixed in commit 8e3d686. Thanks!
