### ISSUE TITLE
[PATCH] If crossbuild, pass *_FOR_BUILD flags to gethost

### ISSUE THREAD

**Issue by josefs10** [tcsh-org/tcsh#104]
Forwarding a debian patch to fix crossbuild failures. `gethost` appears to be using the build arch compiler with the target host arch compiler flags, causing failures with amd64 crossbuild for arm64. The patch passes `*_FOR_BUILD` flags to `gethost` if cross-compiling. @thep

[gethost-crossbuild-flags.patch.txt](https://github.com/tcsh-org/tcsh/files/15326190/gethost-crossbuild-flags.patch.txt)

**Comment by zoulasc** [comment]
committed, thanks!
