### ISSUE TITLE
Removal of union wait

### ISSUE THREAD

**Issue by fweimer** [tcsh-org/tcsh#11]
Following the BSDs and other libc implementations on Linux, glibc will remove union wait.  This will break building tcsh. A patch which fixes this is available here:
* https://build.opensuse.org/package/view_file/home:Andreas_Schwab:Factory/tcsh/union-wait.patch?expand=1

**Comment by zoulasc** [comment]
On Apr 14,  1:48am, notifications@github.com (Florian Weimer) wrote:
-- Subject: [tcsh-org/tcsh] Removal of union wait (#11)

| Following the BSDs and other libc implementations on Linux, glibc will remove union wait.  This will break building tcsh. A patch which fixes this is available here:
| * https://build.opensuse.org/package/view_file/home:Andreas_Schwab:Factory/tcsh/union-wait.patch?expand=1

Thanks,

christos

**Comment by deekej** [comment]
This should be already fixed by: https://github.com/tcsh-org/tcsh/commit/eab72f9797ec4faaf1fb4de491c357f194b84dd6
