### ISSUE TITLE
Fixes for compilation issues in Shift-JIS environments

### ISSUE THREAD

**Issue by T-Nosaka** [tcsh-org/tcsh#115]
In a Shift-JIS environment, the following issues prevent the correct functionality of compilation options. As a result, character encoding is not handled correctly at runtime, causing various issues.

---

#### 1. Incorrect condition for `SIZEOF_WCHAR_T`  
The current code doesn't handle the case when `SIZEOF_WCHAR_T == 4`. The condition should be modified as follows:

**Affected file:** `config_f.h`  
**Before fix:**  
```c
67 # if SIZEOF_WCHAR_T < 4
```
**After fix:**  
```c
67 # if SIZEOF_WCHAR_T <= 4
```
---

#### 2. Misinterpretation of `CODESET type`
`CODESET` is defined as an `enum`, not a macro, so the current condition doesn't work as expected. The condition should be updated as follows:

**Affected file:** `sh.h`  
**Before fix:**  
```c
78 #if defined(KANJI) && defined(WIDE_STRINGS) && defined(HAVE_NL_LANGINFO) && defined(CODESET)
```
**After fix:**  
```c
78 #if defined(KANJI) && defined(WIDE_STRINGS) && defined(HAVE_NL_LANGINFO)
```
---
#### Effect of the fix
With these changes, the program will work correctly in a Shift-JIS environment.
These fixes resolve the following issues:

* Incorrect handling of character encoding
* Malfunction in `KANJI` mode

Please review and consider merging these changes. Thank you.

**Comment by zoulasc** [comment]
Committed, thanks!

christos

**Comment by T-Nosaka** [comment]
Thank you, now I can continue working.
