### ISSUE TITLE
tcsh cannot expand variables containing newlines inside double quotes.

### ISSUE THREAD

**Issue by gregory-nisbet** [tcsh-org/tcsh#12]
The following command works fine and produces a string containing a newline

    % set string_containing_newline = "`printf '\n'`"

The following, however, produces a syntax error

    % set nl = '\
    '
    % set a = "$nl"
    Unmatched '"'

Escaping the newline does not prevent the embedded newline from terminating the string early.

    % set escaped_nl = '\\\
    '
    % set a = "$nl"
    Unmatched '"'

Is this intended behavior?

Tested with 6.18.01 on Linux and 6.17.00 on OS X.

**Comment by zoulasc** [comment]
On Apr 28,  9:13am, notifications@github.com (Gregory Nisbet) wrote:
-- Subject: [tcsh-org/tcsh] tcsh cannot expand variables containing newlines 

| Escaping the newline does not prevent the embedded newline from terminating the string early.
| 
|     % set escaped_nl = '\\\
|     '
|     % set a = "$nl"
|     Unmatched '"'
| 
| Is this intended behavior?

I would not call this intended behavior, but:

[12:24pm] 121#set nl = '\
    '
?     '
[12:26pm] 122#set a = "$nl"
Unmatched '"'.
[12:26pm] 123#set a = "$nl:q"
[12:26pm] 124#echo $a

[12:26pm] 125#echo $a | od -c
0000000   \n                                                            
0000001

I am not sure what will break if we change the semantics.

christos

**Comment by deekej** [comment]
Also, have you tried the latest tcsh version? We have found some issues with escape sequences before. I'm not sure if this will fix it/change it in any way, but I think it's worth giving it shot:

https://github.com/tcsh-org/tcsh/commit/9a763dd9b9b88f9

**Comment by gregory-nisbet** [comment]
I have checked whether this behavior is present in the latest version of master (hash added for reference) and the commit you linked to.

In the current verison of master and the https://github.com/tcsh-org/tcsh/commit/9a763dd9b9b88f9 ```"`prinf '\n'`"``` does result in a quoted multiline string.

current master: https://github.com/tcsh-org/tcsh/commit/097796de628131985db491e0d1dca30363043154

```
% set nl = '\
? '
% set a = "$nl"
Unmatched '"'.
% set a = "$nl:q"
```

previous commit: 9a763dd

```
% set nl = '\
? '
% set a = "$nl"
Unmatched '"'.
% set a = "$nl:q"
```
