### ISSUE TITLE
Segmentation Fault Tcsh 6.19 OS X involving noclobber

### ISSUE THREAD

**Issue by gregory-nisbet** [tcsh-org/tcsh#13]
I'm using tcsh version 6.19 on OS X 10.11.5 (15F34) (latest version available through homebrew).
I've also tested the master branch on this repository, and it has the same problem.

The following series of commands produces a segfault

```
$ tcsh --version
```

tcsh 6.19.00 (Astron) 2015-05-21 (unknown-unknown-bsd44) options
wide,nls,dl,al,kan,sm,rh,color,filec

```
$ tcsh -f
% set noclobber
% touch /tmp/a.csh
% printf '' > /tmp/a.csh
```

produces the output

segmentation fault  tcsh -f
(exit status -11)

Note, however, that when `tcsh` is called non-interactively there is no segfault.

```
$ tcsh -f -c "touch /tmp/a.csh ; printf '' > /tmp/a.csh"
/tmp/a.csh: File exists
```

The /bin/tcsh distributed by the vendor does not exhibit this behavior

$ /bin/tcsh --version
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-apple-darwin) options
wide,nls,dl,al,kan,sm,rh,color,filec

I've managed to track down the line where the segfault is occurring:

In `sh.c` in the definition of `xexit` or `done` on line `sh.c:2451` (https://github.com/tcsh-org/tcsh/blob/master/sh.c#L2451).

**Comment by deekej** [comment]
Reply from Christos: http://mx.gw.com/pipermail/tcsh/2016-May/004982.html

**Comment by gregory-nisbet** [comment]
Is there a workaround other than not using `set noclobber` or combination of compiler flags that'll avoid this issue? I'd like to use the latest version of `tcsh` on OS X because there's a bug where `where` prints every path twice when `set autorehash` is enabled.

Also, is it better to post stuff on the mailing list or here?

**Comment by zoulasc** [comment]
On May 24, 10:28pm, notifications@github.com (Gregory Nisbet) wrote:
-- Subject: Re: [tcsh-org/tcsh] Segmentation Fault Tcsh 6.19 OS X involving n

| Is there a workaround other than not using `set noclobber` or combination of compiler flags that'll avoid this issue? I'd like to use the latest version of `tcsh` on OS X because there's a bug where `where` prints every path twice when `set autorehash` is enabled.
| 
| Also, is it better to post stuff on the mailing list or here?

I think it is better on the mailing list since more people are watching it.
Since it is so easily reproducible we can find a work-around.

christos

**Comment by floam** [comment]
I'd look into whatever Apple did to fix it:

https://opensource.apple.com/source/tcsh/tcsh-66/patches/
This one stands out to me, although it is not present in the latest patches above: https://opensource.apple.com/source/tcsh/tcsh-63.2/patches/sh.proc.c.patch

**Comment by zoulasc** [comment]
On Aug 16,  7:31am, notifications@github.com (Aaron Gyes) wrote:
-- Subject: Re: [tcsh-org/tcsh] Segmentation Fault Tcsh 6.19 OS X involving n

| 
| I'd look into whatever Apple did to fix it:
| 
| https://opensource.apple.com/source/tcsh/tcsh-66/patches/
| This one stands out to me, although it is not present in the latest patches above: https://opensource.apple.com/source/tcsh/tcsh-63.2/patches/sh.proc.c.patch
| 

The host.defs patch is wrong, the other two are in the head of the tree.

christos

**Comment by gregory-nisbet** [comment]
Compile with `./configure <...> CLFAGS='-DDARWIN'` and the resulting binary does not contain this bug.

**Comment by gregory-nisbet** [comment]
closing issue, fixed in latest version.
