### ISSUE TITLE
No startup files included

### ISSUE THREAD

**Issue by Ottaviocr** [tcsh-org/tcsh#19]
I've just installed tsch v. 6.22.00 from pkgsrc on Debian Stretch (distfile ftp://ftp.astron.com/pub/tcsh/tcsh-6.22.00.tar.gz).

No .tcshrc or .cshrc files are included. Is this a choice?

The FAQ file points to:
https://imada.sdu.dk/~blackie/dotfile/ 
and:
http://www.dotfiles.com

Both links are dead.

As long as I know, on Linux systems no .[t]cshrc files are included in /etc/skel, at least not on mine.

**Comment by zoulasc** [comment]
I think that traditionally those files were OS-specific and provided by the package integrators. You should try asking Debian.

Best,

christos

**Comment by Ottaviocr** [comment]
Hi, 

the Debian native package does provide :
/etc/csh.cshrc  /etc/csh.login  /etc/csh.logout

It's the plain vanilla one built from ftp.astron.com that doesn't have them.

Shall I take it that they are not included by choice? If this is the case, so be it, but I'd like a clarification on this issue. Thanks

**Comment by Ottaviocr** [comment]
Would you be willing to import dot.cshrc from:
https://svnweb.freebsd.org/base/head/share/skel/dot.cshrc?view=log

into $PREFIX/share/examples/tcsh/ ?

**Comment by suominen** [comment]
Some of the tcsh defaults could be seen as archaic, maybe providing a sample ~/.tcshrc and ~/.login is useful. So I've committed such.

Maybe this will eventually fix some of the broken and obscure ones provided by e.g. FreeNAS, macOS, and Red Hat.

The dot.tcshrc and dot.login files should appear here on the GitHub mirror shortly.

**Comment by zoulasc** [comment]
Thanks Kim
