### ISSUE TITLE
mailinglist status, website

### ISSUE THREAD

**Issue by ghost** [tcsh-org/tcsh#2]
What happened with the mailinglist? gw.com hosted services (seem to be)^are inaccessible for a very ling time now, same for www.tcsh.org.

**Comment by zoulasc** [comment]
I have moved the mailing list to mailman.astron.com and the bug tracker to bugs.astron.com I will fix the www.tcsh.org wiki shortly.

**Comment by zoulasc** [comment]
There is a separate thread for www.tcsh.org
