### ISSUE TITLE
NLS does not work in some environment.

### ISSUE THREAD

**Issue by kiyotaka4946g** [tcsh-org/tcsh#21]
Hi.

NLS feature tests "/en/LC_MESSAGES/tcsh.cat" at line 182 in sh.c, but nls/Makefile.in install C locale etc and does not install ”/en/LC_MESSAGES/tcsh.cat” .
So some environment e.g. Arch Linux can not use NLS cagtalog.

Would you please fix it?

**Comment by zoulasc** [comment]
Fixed, thanks!

christos
