### ISSUE TITLE
regression: history -S no longer merges command history as described in tcsh man page

### ISSUE THREAD

**Issue by yk-rh** [tcsh-org/tcsh#29]
`https://bugzilla.redhat.com/show_bug.cgi?id=1806769`

**Comment by yk-rh** [comment]
Just wondering if anyone is using this feature - it has been the only reason I still use tcsh because other shells don't support it. Now even tcsh has dropped it.

**Comment by zoulasc** [comment]
Fixed in 6.22.03

**Comment by yk-rh** [comment]
What commit and code line addressed this regression so I can patch my local without the whole update if possible?

**Comment by zoulasc** [comment]
commit 6bc746caad28d0f1ffaf07a4ea1468e8efcc6d52
Author: zoulasc <christos@zoulas.com>
Date:   Sun Feb 23 17:13:23 2020 -0500

    Fix history merging (Brett Frankenberger)
