### ISSUE TITLE
the website www.tcsh.org does not work anymore

### ISSUE THREAD

**Issue by Navis-Raven** [tcsh-org/tcsh#3]
the website www.tcsh.org does not work anymore

![image](https://user-images.githubusercontent.com/15887222/44222131-e89a1580-a183-11e8-9ad3-fb382035ba9e.png)

**Comment by zoulasc** [comment]
@suominen can you please make the DNS for www.tcsh.org point to rebar.astron.com and I will put the content there.

**Comment by suominen** [comment]
Deployed using GitHub Pages.
