### ISSUE TITLE
History breaks when using modifiers ``:gx``, ``:l``...

### ISSUE THREAD

**Issue by jamacku** [tcsh-org/tcsh#37]
**Description**
History breaks when using modifiers like ``:gx`` or ``:l``. Using the upper arrow for re-executing old commands from history doesn't always show the full command (please see below).

**How to reproduce**

- starts with a clean .history file
- setup modifier e.g.: 
``alias postcmd '/bin/echo -n "COMMAND:"'"'"'\!#:-$:gx'"'"''``
- run some commands e.g.: 
``echo 1 2 3 4 5``
``echo "a" 'b' "c"``
- When you want to re-execute some of the commands and hit the upper arrow ``↑``, then the command is missing last _word_.
e.g.: When the last command was ``echo 1 2 3 4 5``, then upon hitting ``↑`` you will get only ``echo 1 2 3 4``. If you then hit the upper arrow one more time you will get the expected result: ``echo 1 2 3 4 5``.

**Expected outcome**
When hitting the upper arrow ``↑``, while modifiers were set, show the full command from history.

**Note**
Originally reported in [rhbz#1906064](https://bugzilla.redhat.com/show_bug.cgi?id=1906064).

**Comment by zoulasc** [comment]
Fixed, thanks! Sorry it took so long.

christos

**Comment by jamacku** [comment]
No problem, thank you Christos!

Patches c14852867786c798f98a23d075e76a2e2acce204 and 04a68ad191cfcb87cdff70a6b913721e423cd28b fixing the issue. Verified on Fedora Rawhide (F35).
