### ISSUE TITLE
Updating prompt, after every command, is that possible?

### ISSUE THREAD

**Issue by DesantBucie** [tcsh-org/tcsh#42]
Let's say i have a code that sets prompt depending on some variable. Now as I can see running `tcsh 6.21.00 (Astron) 2019-05-08 (x86_64-apple-darwin) options wide,nls,dl,bye,al,kan,sm,rh,color,filec` the prompt is only read on shell startup and then if variable changes it won't be updated. Is it possible to make that update when variable changes?

example logic
```
set var=2
if var =~ 2
    set prompt = "blabla"
else
   set prompt ="lalala"

**Comment by zoulasc** [comment]
Perhaps you can use a postcmd alias that sets the prompt? or quote the variable in the prompt so that it is not immediately expanded.

christos

**Comment by DesantBucie** [comment]
I will try that, thanks.
