### ISSUE TITLE
Command history is not saved when shell exited after ctrl+d

### ISSUE THREAD

**Issue by yk-rh** [tcsh-org/tcsh#43]
Is this a bug, feature or something configurable?
I manually compiled 6.22.04 on CentOS6 and it does not exhibit this bad behavior: when I press `ctrl+d` the shell prints `exit` and command history is preserved.
Doing the same on stock Fedora 34 shell prints `logout` on `ctrl+d` and shell does not save command history. 
In both cases `tcsh` is login shell for a user.
Interestingly if I type `logout` or `exit` in Fedora 34 the history is saved.

**Comment by suominen** [comment]
I don't think there is a compile time option that would select such behaviour.

**Comment by yk-rh** [comment]
Updated to Fedora 35, command history is saved in all cases.
version	tcsh 6.22.04 (Astron) 2021-04-26 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,color,filec
