### ISSUE TITLE
Character range test case suggestion

### ISSUE THREAD

**Issue by oddhack** [tcsh-org/tcsh#44]
I ran into a bug on Debian bullseye with tcsh 6.21.00 not properly expanding character classes, e.g.

> mkdir a ; touch a/a a/B  
> echo a/[a-z]  
> a/a a/B

(should just echo 'a/a'). This is not locale-related (occurs in locale "C" as well as "en_US.UTF-8").

While the problem is fixed in TCSH6_23_00, and I've [recommended this to Debian as a fix](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=999754), it would be useful to add this to the test suite if you have time.

Note: I can't verify if this is a problem specifically in the Debian build or in general with 6.21.00, because trying to build from this repository at tag TCSH6_21_00 generates a link error:

```
/usr/bin/ld: tc.sig.o:/home/jon/tools/tcsh/tc.sig.c:59: multiple definition of `handle_interrupt'; sh.o:/home/jon/tools/tcsh/sh.h:569: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:434: tcsh] Error 1
```

Building from the Debian source package does succeed. But whatever the configuration issue was, apparently it has been fixed in TCSH6_23_00 which builds successfully for me on bullseye.

**Comment by suominen** [comment]
Adding a test is a good idea. Would you like to create one for us?

Debian is often reluctant to go with version upgrades, but they might agree to these:
- To fix the character range comparison bug, apply https://github.com/tcsh-org/tcsh/commit/4679bde3e1ceca63d6eb4de5ce41c996405e61aa
- To pass the more stringent compiler options in bullseye, apply https://github.com/tcsh-org/tcsh/commit/6974bc35a5cda6eab748e364bd76a860ca66968b
- To silence the warnings about `_DEFAULT_SOURCE`, apply https://github.com/tcsh-org/tcsh/commit/3a6eadd6a30e40667be14b374a234ddcdeb1e638

All apply cleanly on top of [tcsh-6.21.00.tar.gz](http://ftp.astron.com/pub/tcsh/old/tcsh-6.21.00.tar.gz).

Submitted to [Debian bug 999754](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=999754) as well.

**Comment by oddhack** [comment]
Thanks for submitting to the Debian bug! Regarding a test, the actual test cases are straightforward, but I'm unfamiliar with the test framework being used. Is there documentation on how to write a new test, or at least on the AT_* macros used in the tests/*.at files?

**Comment by suominen** [comment]
The tests use the Autotest macros from Autoconf. The version of Autoconf that ships with Debian 11 is 2.69, so that's probably a good version to look at, so that the tests could run successfully on Travis CI.

Documentation:
https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Using-Autotest.html

**Comment by suominen** [comment]
I noticed that we already had a test for **Filename substitution** (yeah, I haven't looked at all the tests that closely), so I added coverage for this issue to it in 1031f2a3fb430e5fc651be84bdad375ddadf0f26.

**Comment by oddhack** [comment]
Thank you!
