### ISSUE TITLE
config.sub fails if building for "arm64"

### ISSUE THREAD

**Issue by ngam** [tcsh-org/tcsh#46]
For some reason, config.sub expects arm-apple and doesn't accept arm64-apple. 

Failing if it receives `arm64-apple...`

```
checking for a BSD-compatible install... /opt/homebrew/bin/ginstall -c
Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
```

Passing if it receives `arm-apple...`

```
checking for a BSD-compatible install... /opt/homebrew/bin/ginstall -c
checking build system type... arm-apple-darwin21.2.0
checking host system type... arm-apple-darwin21.2.0

```

A quick (and dirty) fix is to replace all mentions of arm to arm64 when building from a place where the machine is set to say arm64, e.g. `mv config.sub config.sub_old; sed 's/arm/arm64/g' config.sub_old > config.sub`. This is our temporary solution at conda-forge, see PR: https://github.com/conda-forge/tcsh-feedstock/pull/9/

It would probably be better if both arm64-apple and arm-apple are supported here. Thanks!

**Comment by zoulasc** [comment]
Should be fixed now!

christos
