### ISSUE TITLE
shlvl test fails with Bash 5.2

### ISSUE THREAD

**Issue by mbakke** [tcsh-org/tcsh#52]
Hi there,

bash 5.2 [changed the way subshells modify SHLVL](https://git.savannah.gnu.org/cgit/bash.git/tree/CHANGES-5.2?id=9cef6d01181525de119832d2b6a925899cdec08e#n305), causing [variables.at](https://github.com/tcsh-org/tcsh/blob/84bcfa8c0e4b75127bb2edd8a604765b03238cef/tests/variables.at#L922-L945) to fail thusly:

```
## ---------------------- ##
## Detailed failed tests. ##
## ---------------------- ##

#                             -*- compilation -*-
225. variables.at:957: testing $ shlvl ...
./variables.at:970: SHLVL=5 tcsh -f shlvl.csh
--- -   2022-09-20 09:03:28.044483058 +0000
+++ /tmp/guix-build-tcsh-6.24.01.drv-0/tcsh-6.24.01/testsuite.dir/at-groups/225/stdout  2022-09-20 09:03:28.040700982 +0000
@@ -1,4 +1,4 @@
-6
+5
 8
 2
 3
225. variables.at:957: 225. $ shlvl (variables.at:957): FAILED (variables.at:970)
```

**Comment by suominen** [comment]
Fixed in 391b04ec25b0d046d532d46a7468fa7a759d0115 — thank you for the report.
