### ISSUE TITLE
skip loading/sourcing of user files

### ISSUE THREAD

**Issue by Zohman** [tcsh-org/tcsh#6]
Hi,

As i've checked the man page there is no flags like --noprofile --norc to disable 
sourcing some files like bash.

i have a scenario where i want to load only global system-wide files like /etc/csh.cshrc, /etc/csh.login , etc..
but skip the user home files ~/.cshrc, ~/.tcshrc, etc.

i understand that i will need to compile from source to achieve this (right..?)
asking if anyone know where can i mark this on source?

Thanks!

**Comment by Zohman** [comment]
i found it,

./tc.const.c:Char STRsldottcshrc[]	= { '/', '.', 't', 'c', 's', 'h', 'r', 'c', '\0' };
./tc.const.c:Char STRsldotcshrc[]	= { '/', '.', 'c', 's', 'h', 'r', 'c', '\0' };
./tc.const.c:Char STRsldotlogin[]	= { '/', '.', 'l', 'o', 'g', 'i', 'n', '\0' };

changed and compiled, worked for me.

**Comment by zoulasc** [comment]
On Aug 23,  9:01pm, notifications@github.com (Zohman) wrote:
-- Subject: [tcsh-org/tcsh] skip loading/sourcing of user files (#6)

| Hi,
| 
| As i've checked the man page there is no flags like --noprofile --norc to disable 
| sourcing some files like bash.
| 
| i have a scenario where i want to load only global system-wide files like /etc/csh.cshrc, /etc/csh.login , etc..
| but skip the user home files ~/.cshrc, ~/.tcshrc, etc.
| 
| i understand that i will need to compile from source to achieve this (right..?)
| asking if anyone know where can i mark this on source?
| 
| Thanks!
| 
| 

Look how the 'fast' variable is being processed in sh.c

christos
