### ISSUE TITLE
Missing definition of functions

### ISSUE THREAD

**Issue by jiahao42** [tcsh-org/tcsh#8]
I didn't find the definition of function `Strbuf_append1` and `Strbuf_terminate` in your repo, please check that.

Thanks.

**Comment by suominen** [comment]
`Strbuf_append1()` (and `strbuf_append1()`): [tc.str.c STRBUF##_append1](https://github.com/tcsh-org/tcsh/blob/1ef6e9d0eef9278829f863fff55755b7a5415b81/tc.str.c#L658-L662)
`Strbuf_terminate()` (and `strbuf_terminate()`): [tc.str.c STRBUF##_terminate](https://github.com/tcsh-org/tcsh/blob/1ef6e9d0eef9278829f863fff55755b7a5415b81/tc.str.c#L652-L655)
