### ISSUE TITLE
Completion for 'ln -s' is incorrect

### ISSUE THREAD

**Issue by hendersj** [tcsh-org/tcsh#80]
When creating a symbolic link in tcsh (6.24.10 on openSUSE Tumbleweed), trying to use tab completion with it results in the following results:

```
[user@hostname ~]$ ln -s 
<link_name>
```

The first parameter after '-s' isn't the link name, though - it's the target.  The link name comes after the target.

I usually work around this by starting with `ln ` and hitting tab to populate the target, add the link name, and then go back and add '-s' into the command, which is not a great workaround.

The distro's entry for this matches what's in this repo, so hoping an upstream fix will help more than just the openSUSE project with it.

**Comment by alzwded** [comment]
[OpenSUSE](https://src.opensuse.org/rpm/tcsh/src/branch/factory/complete.tcsh)'s complete.tcsh doesn't match [upstream](https://github.com/tcsh-org/tcsh/blob/master/complete.tcsh). So it's [fixed upstream](https://github.com/tcsh-org/tcsh/commit/982a43e8dae37722437a9f21d35ab0c8255fd1e0).

Are you sure your entry for ln matches complete.tcsh? I sourced the one in this repo and it works as expected.

**Comment by hendersj** [comment]
Thanks - I must've missed something in my comparison of the configuration.  Will report back in the openSUSE Project.
