### ISSUE TITLE
terminal restores screen after a command exits

### ISSUE THREAD

**Issue by greencardamom** [tcsh-org/tcsh#92]
I am seeking help with this question, replies here, or there. Thank you.

https://stackoverflow.com/questions/77791299/tcsh-terminal-redraw

**Comment by greencardamom** [comment]
The answer is change TERM from xterm to xterm-r5 .. no idea why.

**Comment by greencardamom** [comment]
Closing as resolved unless anyone wants to explain why or other solutions

**Comment by zoulasc** [comment]
You can add a resource to enable/disable switching to the alternate screen. From the manpage:

              Enable Alternate Screen Switching (resource titeInhibit)
                     Enable (or disable) switching between the normal and
                     alternate screens.  This corresponds to the titeInhibit
                     resource.  There is no corresponding command-line option.
